apiVersion: v1
kind: Pod
metadata:
  name: hello-node
  labels:
    app: hello-node
spec:
  containers:
    - name: hello-node
      image: muellermich/hello-node:v1
      ports:
        - containerPort: 8080
